# Generated by Django 2.0.6 on 2019-02-28 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newcarmodel',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
